base_model: meta-llama/Meta-Llama-3-8B-Instruct
# TODO: template? instruct? 
# how many tokens exactly? just whole dataset? Check the paper

# num_epochs: 20
# datasets:
#   - path: vicuna_33b_self_distill.jsonl
#     type: sharegpt
# dataset_prepared_path: last_run_prepared
# val_set_size: 0.01

num_epochs: 1
datasets:
  - path: tatsu-lab/alpaca
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.05

eagle_training: true
num_eagle_layers: 1
hidden_state_loss_coef: 0.1
lm_loss_coef: 1.0

adam_beta1: 0.9
adam_beta2: 0.95
max_grad_norm: 0.5


learning_rate: 3e-5



# USER DEPENDENT
output_dir: /data_persistent2/jamesliu/eagle
wandb_mode: online
wandb_project: eagle_test
wandb_entity:
wandb_watch:
wandb_name: eagle_test
wandb_run_id: eagle_test



load_in_8bit: false
load_in_4bit: false
strict: false





sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true



gradient_accumulation_steps: 1
micro_batch_size: 1

optimizer: paged_adamw_8bit
lr_scheduler: cosine


train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>
